import type { VercelRequest, VercelResponse } from '@vercel/node'

export default async function handler(req: VercelRequest, res: VercelResponse) {
  try {
    const reference = (req.query?.reference as string) || (req.body as any)?.reference
    if (!reference) {
      res.status(400).send('Missing reference')
      return
    }

    const secret = process.env.PAYSTACK_SECRET_KEY
    if (!secret) {
      res.status(500).send('Payment not configured')
      return
    }

    const verifyRes = await fetch(`https://api.paystack.co/transaction/verify/${encodeURIComponent(reference)}`, {
      headers: { Authorization: `Bearer ${secret}` }
    })
    const verifyJson = await verifyRes.json()
    if (!verifyRes.ok || !verifyJson?.data) {
      res.status(400).send('Could not verify transaction')
      return
    }

    const d = verifyJson.data
    const amountNGN = (typeof d.amount === 'number') ? (d.amount / 100).toFixed(2) : d.amount
    const paidAt = d.paid_at || d.paidAt || d.transaction_date || d.created_at

    res.setHeader('Content-Type', 'text/html; charset=utf-8')
    res.status(200).send(`<!doctype html>
      <html>
        <head>
          <meta charset="utf-8" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <title>Receipt • ${reference}</title>
          <style>
            body { font-family: system-ui, -apple-system, Segoe UI, Roboto, sans-serif; background:#f7fafc; margin:0; padding:24px; }
            .card { max-width: 640px; margin: 0 auto; background:#fff; border-radius:16px; box-shadow:0 10px 20px rgba(0,0,0,0.06); padding:24px; }
            h1 { font-size: 20px; margin:0 0 16px; }
            table { width:100%; border-collapse: collapse; }
            td { padding:8px 0; border-bottom: 1px solid #eee; }
            .label { color:#4b5563; }
            .value { color:#111827; font-weight:600; }
            .footer { margin-top:16px; color:#6b7280; font-size:12px; }
            a.btn { display:inline-block; margin-top:16px; background:#2563eb; color:#fff; text-decoration:none; padding:10px 14px; border-radius:8px; }
          </style>
        </head>
        <body>
          <div class="card">
            <h1>Payment Receipt</h1>
            <table>
              <tr><td class="label">Status</td><td class="value">${d.status}</td></tr>
              <tr><td class="label">Reference</td><td class="value">${d.reference}</td></tr>
              <tr><td class="label">Amount</td><td class="value">${amountNGN} ${d.currency}</td></tr>
              <tr><td class="label">Paid At</td><td class="value">${paidAt || ''}</td></tr>
              <tr><td class="label">Channel</td><td class="value">${d.channel}</td></tr>
              <tr><td class="label">Card</td><td class="value">${d.authorization?.brand || ''} •••• ${d.authorization?.last4 || ''}</td></tr>
            </table>
            <div class="footer">
              This receipt is generated by HelloACA using Paystack verify API.
            </div>
            <a class="btn" href="/pricing">Buy more credits</a>
          </div>
        </body>
      </html>`)
  } catch (err) {
    res.status(500).send('Internal error')
  }
}